### ISSUE TITLE
Application exclude

### ISSUE THREAD

**Issue by panbeep** [Mikhail22/drag-scroll--autohotkey#2]
Hi, thank you for the great script! It makes my wacom pen very usable. :)
Is there a way to exclude this script so it doesn't work in certain applications?

**Comment by Mikhail22** [comment]
> Hi, thank you for the great script! It makes my wacom pen very usable. :)
> Is there a way to exclude this script so it doesn't work in certain applications?

You're welcome! 
Yes, you can use Autohotkey's `#If` directive. Google for "creating context-sensitive hotkeys". 
https://www.autohotkey.com/docs/commands/_If.htm

You'll need to add something like this in the beginning of the script:
`#if not  WinActive("ahk_exe yourapp.exe")`
So the script will be deactivated if this app is in focus. "yourapp.exe" is the name of application.
Use window spy tool (right-click on AHK system tray icon and click "window spy") to find the names of active apps.

https://stackoverflow.com/questions/45552452/what-is-au3-spy-exe-where-can-i-find-it
